/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-06-28 00:09:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/view/./outer-nav.jsp", Long.valueOf(1719466509079L));
    _jspx_dependants.put("/WEB-INF/view/./inner-nav.jsp", Long.valueOf(1719532522900L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>다함께 캠핑가자, 캠픽</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div style=\"position:fixed; margin: 13%\">\r\n");
      out.write("	<i class=\"fa-solid fa-quote-left\" style=\"color:white ; font-size: 3em\"></i>\r\n");
      out.write("	<div style=\"color:white ; font-size: 3em ; margin-left: 5px ; text-align: center\">\r\n");
      out.write("	<span style=\"font-size: 1.5em\">캠핑,</span> 복잡한<br/>예약은 이제 그만!<br/> <span style=\"color: gold\">캠픽</span>하세요!</div>\r\n");
      out.write("	<i class=\"fa-solid fa-quote-right\" style=\"color:white ; font-size: 3em ; margin-top: 25px ; margin-left: 430px\"></i>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"fixed-box\">\r\n");
      out.write("		<!-- 임시 CSS 처리 -->\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"./logo.png\" style=\"width: 130px; height: 70px\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/reservation\"><button\r\n");
      out.write("						class=\"button-a\">예약조회</button></a> <a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/alarms\"><button\r\n");
      out.write("						class=\"button-a\">\r\n");
      out.write("						<i class=\"fa-regular fa-bell\"></i>\r\n");
      out.write("					</button></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"margin-top: 10px\">\r\n");
      out.write("			<img src=\"./ad.jpg\"\r\n");
      out.write("				style=\"width: 480px; height: 220px; border-radius: 15px\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"margin-top: 20px\">\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/exhibition/1\"><button\r\n");
      out.write("							class=\"button-b\" style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-person-swimming\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">물놀이가자</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/exhibition/2\"><button\r\n");
      out.write("							class=\"button-b\" style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-mountain-sun\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">만만한캠핑</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/exhibition/3\"><button\r\n");
      out.write("							class=\"button-b\" style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-children\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">키즈캠핑</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a\r\n");
      out.write("						href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search/result?additionalFacilities=pet\"><button\r\n");
      out.write("							class=\"button-b\" style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-dog\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">반려견캠핑</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"\"><button class=\"button-b\"\r\n");
      out.write("							style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-clock\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">빠른예약</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"display: flex; align-items: center; justify-content: space-between; margin-top: 10px\">\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"\"><button class=\"button-c\"\r\n");
      out.write("							style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-fire\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">오토캠핑</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"\"><button class=\"button-c\"\r\n");
      out.write("							style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-campground\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">글램핑</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"\"><button class=\"button-c\"\r\n");
      out.write("							style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-caravan\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">카라반</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/exhibition/4\"><button class=\"button-c\"\r\n");
      out.write("							style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-house-chimney\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">펜션</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"text-align: center\">\r\n");
      out.write("					<a href=\"\"><button class=\"button-c\"\r\n");
      out.write("							style=\"width: 70px; height: 70px\">\r\n");
      out.write("							<i class=\"fa-solid fa-gift\" style=\"font-size: 2em\"></i>\r\n");
      out.write("						</button></a> <br /> <span style=\"font-size: 0.9em;\">이벤트</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"text-align: center; margin-top: 20px; display: flex; align-items: center; justify-content: center; background: #221F18; border-radius: 10px; padding: 15px ; color: white ; margin-bottom: 10px\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<i class=\"fa-solid fa-tents\" style=\"font-size: 3em\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style=\"margin-left: 5px\">\r\n");
      out.write("				예약오픈 일정 한눈에 보기<br /> <small>오픈 일정이 궁금하신가요?</small>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"display: flex; align-items: center; justify-content: space-between; margin: 10px\">\r\n");
      out.write("				<div style=\"font-size: 1.1em; font-weight: bold;\">실시간 캠핑 로그</div>\r\n");
      out.write("				<div style=\"color: darkslateblue ; font-weight: bold\">전체보기</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"fixed-footer\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div\r\n");
      out.write("		style=\"display: flex; align-items: center; justify-content: space-between; width: 120%\">\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button\r\n");
      out.write("				class=\"button-d\" style=\"width: 80px; height: 60px; padding: 5px\">\r\n");
      out.write("				<span class=\"material-symbols-rounded\"> home </span><br /><small>홈</small>\r\n");
      out.write("			</button></a> \r\n");
      out.write("			\r\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\"><button\r\n");
      out.write("				class=\"button-d\" style=\"width: 80px; height: 60px; padding: 5px\">\r\n");
      out.write("				<span class=\"material-symbols-rounded\"> search </span><br /><small>캠핑장 검색</small>\r\n");
      out.write("			</button></a>\r\n");
      out.write("			\r\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product\"><button\r\n");
      out.write("				class=\"button-d\" style=\"width: 80px; height: 60px; padding: 5px\">\r\n");
      out.write("				<span class=\"material-symbols-rounded\"> storefront </span><br /><small>스토어</small>\r\n");
      out.write("			</button></a>\r\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board\"><button\r\n");
      out.write("				class=\"button-d\" style=\"width: 80px; height: 60px; padding: 5px\">\r\n");
      out.write("				<span class=\"material-symbols-rounded\"> edit_square </span><br /><small>캠핑생활</small>\r\n");
      out.write("			</button></a>\r\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage\"><button\r\n");
      out.write("				class=\"button-d\" style=\"width: 80px; height: 60px; padding: 5px\">\r\n");
      out.write("				<span class=\"material-symbols-rounded\"> person </span><br /><small>마이</small>\r\n");
      out.write("			</button></a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
